include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

formatter:
  page_width: 120

linter:
  rules:
    prefer_single_quotes: true
    depend_on_referenced_packages: false
    prefer_relative_imports: true
    prefer_const_constructors: true
    prefer_final_fields: true
    sort_child_properties_last: true
    unawaited_futures: true
    always_declare_return_types: true
    avoid_empty_else: true
    valid_regexps: true
    no_duplicate_case_values: true
    annotate_overrides: true


