name: todo_app
description: "A Todo App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  grpc: ^4.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.6.2
  get_it: ^8.0.2
  injectable: ^2.5.0
  connectivity_plus: ^6.1.0
  flutter_dotenv: ^5.2.1
  dartz: ^0.10.1
  formz: ^0.7.0
  todo_proto:
    path: ./todo_proto

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.8
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  
  assets:
    - .env
